/**
 * Emoji catalog — shared emoji data used by sidebar pickers.
 */

export type EmojiEntry = {
	emoji: string;
	name: string;
	keywords: string;
	search: string;
};

const EMOJI_CATALOG_RAW = [
	["😀", "grinning face", "smile happy grin"],
	["😃", "grinning face with big eyes", "smile happy joy"],
	["😄", "grinning face with smiling eyes", "smile happy laugh"],
	["😁", "beaming face with smiling eyes", "happy grin beam"],
	["😆", "grinning squinting face", "laugh haha funny"],
	["😅", "grinning face with sweat", "nervous relief laugh"],
	["🤣", "rolling on the floor laughing", "rofl laugh funny"],
	["😂", "face with tears of joy", "lol laugh crying"],
	["🙂", "slightly smiling face", "smile calm nice"],
	["🙃", "upside-down face", "silly playful"],
	["🫠", "melting face", "melt awkward hot"],
	["😉", "winking face", "wink playful"],
	["😊", "smiling face with smiling eyes", "blush warm kind"],
	["😇", "smiling face with halo", "angel innocent"],
	["🥰", "smiling face with hearts", "love adore"],
	["😍", "smiling face with heart-eyes", "love wow"],
	["🤩", "star-struck", "excited wow star"],
	["😘", "face blowing a kiss", "kiss love"],
	["😗", "kissing face", "kiss"],
	["☺️", "smiling face", "smile relaxed"],
	["😚", "kissing face with closed eyes", "kiss shy"],
	["😙", "kissing face with smiling eyes", "kiss smile"],
	["🥲", "smiling face with tear", "proud touched"],
	["😋", "face savoring food", "yum tasty"],
	["😛", "face with tongue", "silly playful"],
	["😜", "winking face with tongue", "joke silly"],
	["🤪", "zany face", "crazy goofy"],
	["😝", "squinting face with tongue", "silly goofy"],
	["🤑", "money-mouth face", "money rich"],
	["🤗", "hugging face", "hug friendly"],
	["🤭", "face with hand over mouth", "oops giggle"],
	["🫢", "face with open eyes and hand over mouth", "surprised gasp"],
	["🫣", "face with peeking eye", "peek shy"],
	["🤫", "shushing face", "quiet hush"],
	["🤔", "thinking face", "hmm question"],
	["🫡", "saluting face", "respect salute"],
	["🤐", "zipper-mouth face", "silent secret"],
	["🤨", "face with raised eyebrow", "skeptical doubt"],
	["😐", "neutral face", "meh"],
	["😑", "expressionless face", "blank"],
	["😶", "face without mouth", "speechless"],
	["🫥", "dotted line face", "disappear"],
	["😶‍🌫️", "face in clouds", "foggy absent"],
	["😏", "smirking face", "smirk"],
	["😒", "unamused face", "annoyed"],
	["🙄", "face with rolling eyes", "eyeroll"],
	["😬", "grimacing face", "awkward cringe"],
	["😮‍💨", "face exhaling", "relief sigh"],
	["🤥", "lying face", "lie"],
	["😌", "relieved face", "calm content"],
	["😔", "pensive face", "sad thoughtful"],
	["😪", "sleepy face", "tired"],
	["🤤", "drooling face", "want hungry"],
	["😴", "sleeping face", "sleep zzz"],
	["😷", "face with medical mask", "sick"],
	["🤒", "face with thermometer", "ill fever"],
	["🤕", "face with head-bandage", "hurt"],
	["🤢", "nauseated face", "gross sick"],
	["🤮", "face vomiting", "sick gross"],
	["🤧", "sneezing face", "cold"],
	["🥵", "hot face", "heat"],
	["🥶", "cold face", "freeze"],
	["🥴", "woozy face", "dizzy"],
	["😵", "face with crossed-out eyes", "dizzy"],
	["😵‍💫", "face with spiral eyes", "spiral dizzy"],
	["🤯", "exploding head", "mind blown"],
	["🤠", "cowboy hat face", "cowboy"],
	["🥳", "partying face", "party celebrate"],
	["🥸", "disguised face", "glasses costume"],
	["😎", "smiling face with sunglasses", "cool"],
	["🤓", "nerd face", "smart geek"],
	["🧐", "face with monocle", "inspect fancy"],
	["😕", "confused face", "confused"],
	["🫤", "face with diagonal mouth", "uncertain"],
	["😟", "worried face", "worry"],
	["🙁", "slightly frowning face", "sad"],
	["☹️", "frowning face", "sad frown"],
	["😮", "face with open mouth", "surprised"],
	["😯", "hushed face", "surprised quiet"],
	["😲", "astonished face", "wow shocked"],
	["😳", "flushed face", "embarrassed"],
	["🥺", "pleading face", "please puppy eyes"],
	["🥹", "face holding back tears", "teary emotional"],
	["😦", "frowning face with open mouth", "shocked"],
	["😧", "anguished face", "pain"],
	["😨", "fearful face", "scared"],
	["😰", "anxious face with sweat", "anxious nervous"],
	["😥", "sad but relieved face", "relief sad"],
	["😢", "crying face", "sad cry"],
	["😭", "loudly crying face", "sob cry"],
	["😱", "face screaming in fear", "scream"],
	["😖", "confounded face", "struggle"],
	["😣", "persevering face", "frustrated"],
	["😞", "disappointed face", "sad"],
	["😓", "downcast face with sweat", "stress"],
	["😩", "weary face", "tired upset"],
	["😫", "tired face", "exhausted"],
	["🥱", "yawning face", "sleepy"],
	["😤", "face with steam from nose", "determined angry"],
	["😡", "pouting face", "angry mad"],
	["😠", "angry face", "angry"],
	["🤬", "face with symbols on mouth", "swear rage"],
	["😈", "smiling face with horns", "devil"],
	["👿", "angry face with horns", "devil angry"],
	["💀", "skull", "dead spooky"],
	["☠️", "skull and crossbones", "danger poison"],
	["👻", "ghost", "spooky halloween"],
	["👽", "alien", "space"],
	["🤖", "robot", "bot ai"],
	["💩", "pile of poo", "poop funny"],
	["🐶", "dog face", "dog pet animal"],
	["🐱", "cat face", "cat pet animal"],
	["🐭", "mouse face", "mouse animal"],
	["🐹", "hamster face", "hamster pet"],
	["🐰", "rabbit face", "bunny"],
	["🦊", "fox", "fox animal"],
	["🐻", "bear", "bear animal"],
	["🐼", "panda", "panda animal"],
	["🐨", "koala", "koala animal"],
	["🐯", "tiger face", "tiger animal"],
	["🦁", "lion", "lion animal"],
	["🐮", "cow face", "cow animal"],
	["🐷", "pig face", "pig animal"],
	["🐸", "frog", "frog animal"],
	["🐵", "monkey face", "monkey animal"],
	["🐔", "chicken", "bird animal"],
	["🐧", "penguin", "penguin bird"],
	["🐦", "bird", "bird animal"],
	["🐤", "baby chick", "chick bird"],
	["🦄", "unicorn", "unicorn fantasy"],
	["🐝", "honeybee", "bee bug"],
	["🦋", "butterfly", "butterfly bug"],
	["🐢", "turtle", "turtle animal"],
	["🐙", "octopus", "ocean sea"],
	["🦀", "crab", "crab sea"],
	["🐬", "dolphin", "sea animal"],
	["🐳", "spouting whale", "whale sea"],
	["🦭", "seal", "seal sea"],
	["🌱", "seedling", "plant grow"],
	["🌿", "herb", "plant green"],
	["🍀", "four leaf clover", "luck plant"],
	["🌵", "cactus", "desert plant"],
	["🌴", "palm tree", "tree vacation"],
	["🌳", "deciduous tree", "tree nature"],
	["🌲", "evergreen tree", "tree pine"],
	["🌸", "cherry blossom", "flower pink"],
	["🌼", "blossom", "flower yellow"],
	["🌻", "sunflower", "flower sun"],
	["🌞", "sun with face", "sun weather"],
	["🌝", "full moon face", "moon night"],
	["🌈", "rainbow", "rainbow color"],
	["⭐", "star", "star favorite"],
	["✨", "sparkles", "sparkle magic"],
	["⚡", "high voltage", "lightning energy"],
	["🔥", "fire", "fire hot"],
	["☄️", "comet", "space star"],
	["🌊", "water wave", "wave ocean"],
	["🍎", "red apple", "fruit apple"],
	["🍊", "tangerine", "orange fruit"],
	["🍋", "lemon", "fruit sour"],
	["🍉", "watermelon", "fruit summer"],
	["🍇", "grapes", "fruit"],
	["🍓", "strawberry", "fruit berry"],
	["🫐", "blueberries", "fruit berry"],
	["🍒", "cherries", "fruit"],
	["🍍", "pineapple", "fruit tropical"],
	["🥭", "mango", "fruit tropical"],
	["🥑", "avocado", "food"],
	["🍔", "hamburger", "burger food"],
	["🍟", "french fries", "fries food"],
	["🍕", "pizza", "food slice"],
	["🌮", "taco", "food mexican"],
	["🌯", "burrito", "food mexican"],
	["🥪", "sandwich", "food lunch"],
	["🍣", "sushi", "food japan"],
	["🍜", "steaming bowl", "ramen noodles"],
	["☕", "hot beverage", "coffee drink"],
	["🍵", "teacup without handle", "tea drink"],
	["🧋", "bubble tea", "boba drink"],
	["🥤", "cup with straw", "drink soda"],
	["🍺", "beer mug", "beer drink"],
	["🍷", "wine glass", "wine drink"],
	["🥂", "clinking glasses", "celebrate toast"],
	["🧠", "brain", "brain thinking"],
	["💬", "speech balloon", "chat talk"],
	["💭", "thought balloon", "thought idea"],
	["💡", "light bulb", "idea bright"],
	["🔦", "flashlight", "light tool"],
	["🕯️", "candle", "light calm"],
	["💻", "laptop", "computer work"],
	["🖥️", "desktop computer", "computer desktop"],
	["⌨️", "keyboard", "typing"],
	["🖱️", "computer mouse", "mouse computer"],
	["📱", "mobile phone", "phone smartphone"],
	["☎️", "telephone", "phone call"],
	["📷", "camera", "photo"],
	["📸", "camera with flash", "photo"],
	["🎥", "movie camera", "video film"],
	["🎧", "headphone", "music audio"],
	["🎤", "microphone", "audio sing"],
	["📦", "package", "box shipping"],
	["📁", "file folder", "folder file"],
	["🗂️", "card index dividers", "organize"],
	["📝", "memo", "write notes"],
	["📓", "notebook", "notes"],
	["📚", "books", "read study"],
	["📌", "pushpin", "pin mark"],
	["✂️", "scissors", "cut"],
	["🖌️", "paintbrush", "paint art"],
	["🎨", "artist palette", "art color"],
	["🧰", "toolbox", "tools fix"],
	["🔧", "wrench", "tool fix"],
	["🔨", "hammer", "tool build"],
	["🪛", "screwdriver", "tool fix"],
	["🛠️", "hammer and wrench", "repair build"],
	["⚙️", "gear", "settings tool"],
	["🔒", "locked", "secure private"],
	["🔓", "unlocked", "open secure"],
	["🔑", "key", "access unlock"],
	["🪄", "magic wand", "magic creative"],
	["🎯", "bullseye", "target focus"],
	["🏁", "chequered flag", "finish race"],
	["🚀", "rocket", "launch space"],
	["🛰️", "satellite", "space orbit"],
	["✈️", "airplane", "travel flight"],
	["🚗", "automobile", "car drive"],
	["🚲", "bicycle", "bike ride"],
	["🛸", "flying saucer", "ufo space"],
	["🏠", "house", "home"],
	["🏡", "house with garden", "home"],
	["🏢", "office building", "office work"],
	["🌃", "night with stars", "city night"],
	["🌅", "sunrise", "morning"],
	["🏝️", "desert island", "island vacation"],
	["🏔️", "snow-capped mountain", "mountain nature"],
	["🧭", "compass", "navigate direction"],
	["⏳", "hourglass", "time waiting"],
	["⌛", "hourglass done", "time"],
	["⏰", "alarm clock", "clock time"],
	["📅", "calendar", "date schedule"],
	["✅", "check mark button", "done yes"],
	["🆕", "new button", "new fresh"],
	["❗", "exclamation mark", "important"],
	["❓", "question mark", "question"],
	["❤️", "red heart", "love heart"],
	["🧡", "orange heart", "heart"],
	["💛", "yellow heart", "heart"],
	["💚", "green heart", "heart"],
	["🩵", "light blue heart", "heart"],
	["💙", "blue heart", "heart"],
	["💜", "purple heart", "heart"],
	["🖤", "black heart", "heart"],
	["🤍", "white heart", "heart"],
	["🤎", "brown heart", "heart"],
	["💥", "collision", "boom"],
	["🎉", "party popper", "celebrate party"],
	["🎊", "confetti ball", "celebrate party"],
	["🏆", "trophy", "win award"],
	["🥇", "first place medal", "gold award"],
	["🎮", "video game", "gaming"],
	["🧩", "puzzle piece", "puzzle"],
	["♟️", "chess pawn", "chess strategy"],
	["🎵", "musical note", "music"],
	["🎶", "musical notes", "music"],
	["📈", "chart increasing", "growth analytics"],
	["📉", "chart decreasing", "analytics"],
] as const;

export const EMOJI_CATALOG: EmojiEntry[] = EMOJI_CATALOG_RAW.map(([emoji, name, keywords]) => ({
	emoji,
	name,
	keywords,
	search: `${emoji} ${name} ${keywords}`.toLowerCase(),
}));
